apiVersion: v1
kind: Service
metadata:
  name: backbone
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: backbone  
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
